---
# tasks file for roles/modulos-apache
# Habiliar modulos apache para proxy reverso y balanceo de carga

- name: Enable apache modules Redhat
  apache2_module:
    state: present
    name: "{{ item }}"
  loop: "{{ modulos }}"

  notify: Restart httpd
  when: ansible_facts['os_family'] == "RedHat"


- name: Enable apache modules Debian
  apache2_module:
    state: present
    name: "{{ item }}"
  loop: "{{ modulos }}"
  notify: Restart apache
  when: ansible_facts['os_family'] == "Debian"

